name: ai
channels:
  - defaults
dependencies:
  - ipywidgets
  - jupyter
  - matplotlib
  - nb_conda
  - nltk
  - notebook
  - numpy
  - pandas
  - pip
  - python
  - scikit-learn
  - scipy
  - pip:
    - keras
    - tensorflow
   